## Initialization

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## Data Loading

In [3]:
df = pd.read_csv(
	'Amazon_Reviews.csv',
	encoding='utf-8',
	encoding_errors='replace',
	on_bad_lines='skip',
	engine='python'
)

In [4]:
df.head()

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience
0,Eugene ath,/users/66e8185ff1598352d6b3701a,US,1 review,2024-09-16T13:44:26.000Z,Rated 1 out of 5 stars,A Store That Doesn't Want to Sell Anything,"I registered on the website, tried to order a ...","September 16, 2024"
1,Daniel ohalloran,/users/5d75e460200c1f6a6373648c,GB,9 reviews,2024-09-16T18:26:46.000Z,Rated 1 out of 5 stars,Had multiple orders one turned up and…,Had multiple orders one turned up and driver h...,"September 16, 2024"
2,p fisher,/users/546cfcf1000064000197b88f,GB,90 reviews,2024-09-16T21:47:39.000Z,Rated 1 out of 5 stars,I informed these reprobates,I informed these reprobates that I WOULD NOT B...,"September 16, 2024"
3,Greg Dunn,/users/62c35cdbacc0ea0012ccaffa,AU,5 reviews,2024-09-17T07:15:49.000Z,Rated 1 out of 5 stars,Advertise one price then increase it on website,I have bought from Amazon before and no proble...,"September 17, 2024"
4,Sheila Hannah,/users/5ddbe429478d88251550610e,GB,8 reviews,2024-09-16T18:37:17.000Z,Rated 1 out of 5 stars,If I could give a lower rate I would,If I could give a lower rate I would! I cancel...,"September 16, 2024"

In [5]:
df.columns

Index(['Reviewer Name', 'Profile Link', 'Country', 'Review Count',
       'Review Date', 'Rating', 'Review Title', 'Review Text',
       'Date of Experience'],
      dtype='object')

## Data Conditioning

In [6]:
df = df[['Country','Review Count', 'Rating', 'Review Text','Review Date']].copy()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       21054 non-null  object
 1   Review Count  21055 non-null  object
 2   Rating        21055 non-null  object
 3   Review Text   21055 non-null  object
 4   Review Date   21055 non-null  object
dtypes: object(5)
memory usage: 828.8+ KB

In [8]:
# df.drop(columns=['Review Count','Rating'], inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       21054 non-null  object
 1   Review Count  21055 non-null  object
 2   Rating        21055 non-null  object
 3   Review Text   21055 non-null  object
 4   Review Date   21055 non-null  object
dtypes: object(5)
memory usage: 828.8+ KB

In [10]:
## Rating count 
df['Review Count']

0          1 review
1         9 reviews
2        90 reviews
3         5 reviews
4         8 reviews
            ...
21209      1 review
21210     2 reviews
21211     3 reviews
21212    82 reviews
21213     2 reviews
Name: Review Count, Length: 21214, dtype: object

In [11]:
df['Review Count'].value_counts()

Review Count
1 review       5761
2 reviews      3593
3 reviews      2255
4 reviews      1491
5 reviews      1095
               ...
319 reviews       1
150 reviews       1
217 reviews       1
147 reviews       1
163 reviews       1
Name: count, Length: 177, dtype: int64

### Pipeline for the rating or sentiment analysis of the reviews 
- 4 - 5 stars - Positive
- 3 stars - Neutral
- 1 - 2 stars - Negative

The steps we will follow are:
1. Extract the rating value from the "Rating" column.
2. Create a new column "sentiment" based on the rating value.
3. Analyze the distribution of sentiments in the dataset.
4. lowecase the reviews and remove stop words for further analysis.
5. use TF-IDF vectorization to convert the text data into numerical format for modeling.
6. Train a machine learning model (e.g., Logistic Regression and decision tree) to predict the sentiment based on the reviews.
7. Use SVM to predict the sentiment using SVM and compare the results with the previous models.
8. Evaluate the performance of the models using metrics such as accuracy, precision, recall, and F1-score.

In [12]:
part = df['Review Count'].str.split(' ', expand=True)
# print(part.head())
df['Count'] = part[0].astype('Int32')
# print(df['Review Count'],df['Count'])

In [13]:
rating_parts = df['Rating'].astype(str).str.split(" ",expand=True)
# print(rating_parts)
df['rating'] = rating_parts[1].astype('Int32')
df['total_rating'] = rating_parts[4].astype('Int32')
# print(df['rating'],df['total_rating'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       21054 non-null  object
 1   Review Count  21055 non-null  object
 2   Rating        21055 non-null  object
 3   Review Text   21055 non-null  object
 4   Review Date   21055 non-null  object
 5   Count         21055 non-null  Int32
 6   rating        21055 non-null  Int32
 7   total_rating  21055 non-null  Int32
dtypes: Int32(3), object(5)
memory usage: 1.1+ MB

In [15]:
df.drop(columns=['Review Count','Rating'], inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       21054 non-null  object
 1   Review Text   21055 non-null  object
 2   Review Date   21055 non-null  object
 3   Count         21055 non-null  Int32
 4   rating        21055 non-null  Int32
 5   total_rating  21055 non-null  Int32
dtypes: Int32(3), object(3)
memory usage: 808.1+ KB

In [17]:

df['Review Date'] = pd.to_datetime(df['Review Date'], errors='coerce')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       21054 non-null  object
 1   Review Text   21055 non-null  object
 2   Review Date   21055 non-null  datetime64[ns, UTC]
 3   Count         21055 non-null  Int32
 4   rating        21055 non-null  Int32
 5   total_rating  21055 non-null  Int32
dtypes: Int32(3), datetime64[ns, UTC](1), object(2)
memory usage: 808.1+ KB

In [19]:
df.describe()

           Count    rating  total_rating
count    21055.0   21055.0       21055.0
mean     8.48872  2.186654           5.0
std    18.239247  1.676769           0.0
min          1.0       1.0           5.0
25%          1.0       1.0           5.0
50%          3.0       1.0           5.0
75%          8.0       4.0           5.0
max        633.0       5.0           5.0

### Null value check or missing value check

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       21054 non-null  object
 1   Review Text   21055 non-null  object
 2   Review Date   21055 non-null  datetime64[ns, UTC]
 3   Count         21055 non-null  Int32
 4   rating        21055 non-null  Int32
 5   total_rating  21055 non-null  Int32
dtypes: Int32(3), datetime64[ns, UTC](1), object(2)
memory usage: 808.1+ KB

In [21]:
df.isnull().sum()

Country         160
Review Text     159
Review Date     159
Count           159
rating          159
total_rating    159
dtype: int64

In [22]:
df.dropna(inplace=True)

In [23]:
df.isnull().sum()

Country         0
Review Text     0
Review Date     0
Count           0
rating          0
total_rating    0
dtype: int64

In [24]:
df.shape

(21054, 6)

In [25]:
df['rating'].value_counts()

rating
1    13123
5     4527
4     1292
2     1227
3      885
Name: count, dtype: Int64

In [26]:
sentiment = []
for i in df['rating']:
    if i >= 4:
        sentiment.append('positive')
    elif i == 3:
        sentiment.append('neutral')
    else:
        sentiment.append('negative')

In [27]:
df['sentiment'] = sentiment

In [28]:
df['sentiment'].value_counts()

sentiment
negative    14350
positive     5819
neutral       885
Name: count, dtype: int64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21054 entries, 0 to 21213
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       21054 non-null  object
 1   Review Text   21054 non-null  object
 2   Review Date   21054 non-null  datetime64[ns, UTC]
 3   Count         21054 non-null  Int32
 4   rating        21054 non-null  Int32
 5   total_rating  21054 non-null  Int32
 6   sentiment     21054 non-null  object
dtypes: Int32(3), datetime64[ns, UTC](1), object(3)
memory usage: 1.1+ MB

### Encoding

In [30]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [31]:
## Encoding
onehot = OneHotEncoder()
country_encode = onehot.fit_transform(df[['Country']])

In [32]:
le = LabelEncoder()
sentiment_encoded = le.fit_transform(df[['sentiment']])

/home/dharmender/anaconda3/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
tfidf = TfidfVectorizer()

In [35]:
df.rename(columns={'Review Text':'review_text'}, inplace=True)

In [36]:
df['review_text'] = df['review_text'].str.lower().replace('[^\w\s]','')

##  ML Model Building

In [37]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

In [38]:
x = tfidf.fit_transform(df['review_text'])
y = sentiment_encoded

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [40]:
x_train.shape

(16843, 28865)

## Logistic Regression Modelling

In [41]:
lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [42]:
y_pred_lr = lr.predict(x_test)

### Decision Tree Modelling

In [43]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

## SVM Modelling

In [44]:
# svm = SVC()
# svm.fit(x_train, y_train)

### Matrix Evaluation

In [45]:
# print(f"Accuracy of Logistic Regression:\n {classification_report(y_test, y_pred_lr)}")
print(f"Accuracy of Logistic Regression:\n {accuracy_score(y_test, y_pred_lr)}")

Accuracy of Logistic Regression:
 0.89978627404417

In [46]:
# print(f"Decision Tree Classification Report:\n {classification_report(y_test, dt.predict(x_test))}")
print(f"Accuracy of Decision Tree:\n {accuracy_score(y_test, dt.predict(x_test))}")

Accuracy of Decision Tree:
 0.8014723343623842

## Dumping the encoders into pickle files for future use

In [47]:
import pickle 
pickle.dump(tfidf, open('tfidf_vectorizer.pkl', 'wb'))
pickle.dump(le, open('label_encoder.pkl', 'wb'))

In [48]:
pickle.dump(lr, open('logistic_regression_model.pkl', 'wb'))
pickle.dump(dt, open('decision_tree_model.pkl', 'wb'))

In [49]:
# df.describe()

In [50]:
# Convert strings like '1 out of 5 stars' into numeric columns
# rating_parts = df['Rating'].astype(str).str.extract(r'(\d+(?:\.\d+)?)\s*out of\s*(\d+(?:\.\d+)?)', expand=True)

# df['rating_value'] = pd.to_numeric(rating_parts[0], errors='coerce')
# df['rating_scale'] = pd.to_numeric(rating_parts[1], errors='coerce')

# # Optional: normalized rating from 0 to 1
# df['rating_normalized'] = df['rating_value'] / df['rating_scale']

# df[['Rating', 'rating_value', 'rating_scale', 'rating_normalized']].head()